### ISSUE TITLE
Bug: server not working

### ISSUE THREAD

**Issue by thibautjombart** [thibautjombart/treespace#4]
```
> treespaceServer()

Listening on http://127.0.0.1:3182
Loading required package: rgl
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rgl’
Warning: Error in rglwidgetOutput: could not find function "rglwidgetOutput"
Stack trace (innermost first):
    66: tag
    65: tags$div
    64: div
    63: conditionalPanel
    62: tag
    61: tags$div
    60: div
    59: mainPanel
    58: tag
    57: tags$div
    56: div
    55: tag
    54: tags$div
    53: div
    52: tagList
    51: attachDependencies
    50: bootstrapPage
    49: pageWithSidebar
    48: tag
    47: tags$div
    46: div
    45: tabPanel
    44: navbarPage
    43: shinyUI
     2: runApp
     1: treespaceServer

```
Looks like a dep on 'rgl' is not declared? Though if possible it would be nice not to depend on it at all.

**Comment by MichelleKendall** [comment]
Thanks for this. I have tried moving rgl from "suggests" to "imports" - it turns out that rgl requires an extra installation step on macs of downloading XQuartz so I think that's part of the problem. Thankfully it does issue an informative error message. It would be nice to remove the dependency altogether but I really want to keep the 3D plotting available in the Shiny server and I'm not aware of a good alternative. I think that's cured it but I'll do more thorough checks before updating on CRAN.

On a related note, rgl was also the source of the warnings we get on CRAN checks for certain operating systems about building the Dengue vignette. After trying lots of things I have with reluctance just removed the 3D example from the vignette, but if anyone knows how I can put it back in that would be great. It builds fine on some operating systems.

**Comment by MichelleKendall** [comment]
... and I somehow introduced an error. I'm going to revert the latest commit for now but I'll come back to it asap!

**Comment by thibautjombart** [comment]
The rgl dep is a pain on linux too. Thing is, as it is now the package does not, strictly speaking, work: one of the main function issues on error from a fresh install with all deps in. We get away with it because CRAN is oblivious to whatever happens in the shiny app.

**Comment by MichelleKendall** [comment]
Agreed - it's important we fix this asap. I'm attempting it now.

**Comment by MichelleKendall** [comment]
I have made various changes to the vignettes to ensure they build on all operating systems. 

By moving "rgl" from "suggests" to "imports" I have hopefully avoided getting the above error, but now we get the warning:
```
Warning in rgl.init(initValue, onlyNULL) :
  RGL: unable to open X11 display
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE
```
whenever you load treespace (on some operating systems). Sigh. So it technically works but it's really ugly. Can you think of a way to improve on that?!

**Comment by thibautjombart** [comment]
I'm not sure when you get this: on `library(treespace)` , or starting the shiny app?

**Comment by MichelleKendall** [comment]
Yes, on `library(treespace)` for me. Do you not get that?

**Comment by MichelleKendall** [comment]
Rebooting after the installation of XQuartz seems to have silenced this warning message for me, thankfully. I'm going to run the final checks and then submit the update to CRAN.
